app:
  name: data-platform

paths:
  raw: data/raw
  bronze: data/bronze
  silver: data/silver
  gold: data/gold
  stream:
    input: data/stream/stream_input
    output: data/stream/stream_output
    checkpoint: data/stream/stream_checkpoint
    late_output: data/stream/stream_late_output
    late_checkpoint: data/stream/stream_late_checkpoint

spark:
  app_name: data-platform
  master: local[*]
  configs:
    spark.sql.shuffle.partitions: 4
    spark.sql.execution.arrow.pyspark.enabled: true
    jar: jars/mysql-connector-j-8.3.0.jar
    spark.sql.adaptive.enabled: true
    spark.sql.adaptive.skewJoin.enabled: true
    spark.sql.adaptive.coalescePartitions.enabled: true

mysql:
  url: jdbc:mysql://localhost:3306/data_platform
  driver: com.mysql.cj.jdbc.Driver
  database: data_platform